#spring.freemarker.template-loader-path = classpath:/web/
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.dir}


#spring.redisson.address = 127.0.0.1:6379
#
file:
  dir: /Users/liaojin/Desktop/officeFile/
#file.dir = D:/yy/filePreview/
## openoffice
office:
  home: /Applications/OpenOffice.app/Contents/
#office.home = C:/Program Files (x86)/OpenOffice 4

server:
  tomcat:
    uri-encoding: UTF-8
converted:
  file:
    charset: UTF-8

##
simText: txt,html,xml,java,properties,sql
media: mp3,mp4,flv,rmvb
